version: 0.9
cloudflare: #CloudflareAPIの資格情報
  auth:
    mode: "token" #tokenまたはaccount
    email: "" #accountの場合必須
    appKey: "" #accountの場合必須
    token: "" #tokenの場合必須
  record: #更新するDNSレコードの設定
    zoneId: ""
    recordId: ""
    name: ""
loopInterval: 1 #秒ごとにアドレス更新を確認
interface: "" #DHCPで変動アドレスが設定されているインターフェス(例: ens18)
onlineCheckAddress: "2606:4700:4700::1111" #インターネット接続の確認先
logPath: "/var/log/v6dnsupdater" #ログの保存先